name: Document Conversion

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: maxheld83/pandoc@v2
        with:
          args: pandoc notes.md -o FYP-Report.pdf --from markdown --template eisvogel --table-of-contents --highlight-style my_style.theme -V fontsize=10pt 
